/*
Author: Gavin Witsken
Program: ish - simple shell
File: main.c
*/

typedef enum ISH_LEX_ERROR {
    ISH_LEX_ERR_OPEN_SINGLE_QUOTE,
    ISH_LEX_ERR_OPEN_DOUBLE_QUOTE,
    ISH_LEX_ERR_OPEN_BACK_QUOTE,
    ISH_LEX_ERR_OPEN_BACKSLASH,
    ISH_LEX_ERR_OPEN_CURLY_BRACE,
    ISH_LEX_ERR_OPEN_SQUARE_BRACKET,
    ISH_LEX_ERR_OPEN_PAREN,
    ISH_LEX_ERR_NONE
} ISH_LEX_ERROR_T;